trigger:
- main

stages:
- stage: A
  jobs:
  - job: Work
    steps:
      - bash: echo "circle ci runs first"
  - job: A
    steps:
    - bash: echo "A"

- stage: B
  jobs:
  - job: B
    steps:
    - bash: echo "B"
