jobs:
- job: DeployJob
  displayName: 'Deploy to Azure Web App'

  steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Playground'
        appType: 'webApp'
        WebAppName: 'app-pacman-api'
        packageForLinux: '$(build.artifactStagingDirectory)/**/*.zip'